/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proj;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

import java.awt.event.*;
import java.io.File;
import java.io.FileWriter;

import java.sql.DriverManager;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author irosh
 */
public class ADDADMIN extends javax.swing.JFrame {

    /**
     * Creates new form ADDADMIN
     */
    
    Connection conn;
    PreparedStatement pst;
    public ADDADMIN() {
        initComponents();
    }
    
    int adminID;
    Locale ll;
    public ADDADMIN(int adID,Locale lcl) {
        Locale.setDefault(lcl);
        ll=lcl;
        initComponents();
        adminID=adID;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextFieldADMINID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Textfield_ADMINNAME = new javax.swing.JTextField();
        ButtonSignUp_Signuppanel = new javax.swing.JButton();
        ButtonReset_Signuppanel = new javax.swing.JButton();
        LabelLogin = new javax.swing.JLabel();
        LabelBACK_depositpanel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Textfield_Password = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\irosh\\OneDrive\\Desktop\\JAVA\\Project\\Logo v3.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle"); // NOI18N
        jLabel2.setText(bundle.getString("ADDADMIN.jLabel2.text")); // NOI18N

        TextFieldADMINID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextFieldADMINIDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldADMINIDKeyTyped(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(bundle.getString("ADDADMIN.jLabel3.text")); // NOI18N

        ButtonSignUp_Signuppanel.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        ButtonSignUp_Signuppanel.setForeground(new java.awt.Color(51, 0, 153));
        ButtonSignUp_Signuppanel.setText(bundle.getString("ADDADMIN.ButtonSignUp_Signuppanel.text")); // NOI18N
        ButtonSignUp_Signuppanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSignUp_SignuppanelActionPerformed(evt);
            }
        });

        ButtonReset_Signuppanel.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        ButtonReset_Signuppanel.setForeground(new java.awt.Color(51, 0, 153));
        ButtonReset_Signuppanel.setText(bundle.getString("ADDADMIN.ButtonReset_Signuppanel.text")); // NOI18N
        ButtonReset_Signuppanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonReset_SignuppanelActionPerformed(evt);
            }
        });

        LabelLogin.setFont(new java.awt.Font("Broadway", 0, 18)); // NOI18N
        LabelLogin.setForeground(new java.awt.Color(255, 255, 255));
        LabelLogin.setText(bundle.getString("ADDADMIN.LabelLogin.text")); // NOI18N

        LabelBACK_depositpanel.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        LabelBACK_depositpanel.setForeground(new java.awt.Color(255, 0, 0));
        LabelBACK_depositpanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelBACK_depositpanel.setText(bundle.getString("ADDADMIN.LabelBACK_depositpanel.text")); // NOI18N
        LabelBACK_depositpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelBACK_depositpanelMouseClicked(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(bundle.getString("ADDADMIN.jLabel4.text")); // NOI18N

        Textfield_Password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Textfield_PasswordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Textfield_PasswordKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldADMINID)
                            .addComponent(Textfield_ADMINNAME)
                            .addComponent(Textfield_Password)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(ButtonSignUp_Signuppanel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonReset_Signuppanel, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(93, 93, 93))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(190, 190, 190))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelBACK_depositpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ButtonReset_Signuppanel, ButtonSignUp_Signuppanel});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(LabelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldADMINID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Textfield_ADMINNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Textfield_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSignUp_Signuppanel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonReset_Signuppanel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelBACK_depositpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void Clear(){
        TextFieldADMINID.setText("");
        Textfield_ADMINNAME.setText("");
        Textfield_Password.setText("");
        
        
    }
    
    private void LabelBACK_depositpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelBACK_depositpanelMouseClicked
        // TODO add your handling code here:
        new ADMIN(adminID,ll).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabelBACK_depositpanelMouseClicked

    private void ButtonReset_SignuppanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonReset_SignuppanelActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_ButtonReset_SignuppanelActionPerformed

    private void ButtonSignUp_SignuppanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSignUp_SignuppanelActionPerformed
        // TODO add your handling code here:
        String thisaccno=TextFieldADMINID.getText();

        try{
            String url="jdbc:derby://localhost:1527/BankABC";
            Connection con=DriverManager.getConnection(url, "IROSH", "abc@123");
            java.sql.Statement stmnt= con.createStatement();
            String qry="SELECT * FROM IROSH.ADMIN";
            ResultSet RS=stmnt.executeQuery(qry); //pointer start from -1.returns false when there are no more rows
            boolean accnowaradi=true;
            while(RS.next()==true){
                String accnoo=RS.getString("ADMIN_ID");

                if(thisaccno.equalsIgnoreCase(accnoo)){
                    accnowaradi=false;
                    break;

                }
                else{
                    accnowaradi= true;

                }
            }

            if(accnowaradi==false){
                JOptionPane.showMessageDialog(rootPane, "ADMIN ID is already in Use.Try again", "Error", JOptionPane.OK_OPTION);

            }
            if(accnowaradi==true){
                try {

                    if(TextFieldADMINID.getText().isEmpty() || Textfield_ADMINNAME.getText().isEmpty() || Textfield_Password.getText().isEmpty() ){
                        JOptionPane.showMessageDialog(rootPane, "Missing Information", "Error", JOptionPane.NO_OPTION);
                    }
                    else{
                        url = "jdbc:derby://localhost:1527/BankABC";
                        conn = DriverManager.getConnection(url, "IROSH", "abc@123");
                        pst = conn.prepareStatement("INSERT INTO IROSH.ADMIN VALUES (?,?,?)");
                        pst.setInt(1, Integer.parseInt(TextFieldADMINID.getText()));
                        pst.setString(2, Textfield_ADMINNAME.getText());
                        pst.setInt(3, Integer.parseInt(Textfield_Password.getText()));
                        
                        pst.executeUpdate();

                        JOptionPane.showMessageDialog(rootPane, "Account added");
                        Clear();

                        //                Date d= new Date();
                        //                DateFormat df= DateFormat.getDateTimeInstance(DateFormat.FULL, DateFormat.FULL);
                        //                File f=new File("C:\\Users\\irosh\\OneDrive\\Desktop\\Log.txt");
                        //                FileWriter fw=new FileWriter(f, true); //When 2nd parameter is true, files write from the end of the index and wont replace values
                        //                fw.write("Record added "+TextFieldID.getText()+" "+df.format(d)+"\n" );
                        //                fw.flush();
                        //                fw.close();
                    }

                }catch(Exception e){
                    JOptionPane.showMessageDialog(rootPane, e.getMessage(), "error", JOptionPane.ERROR_MESSAGE);
                }

            }

        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_ButtonSignUp_SignuppanelActionPerformed

    private void TextFieldADMINIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldADMINIDKeyTyped
//         TODO add your handling code here:
        char c= evt.getKeyChar();

        if(!Character.isDigit(c)){
            evt.consume();}
    }//GEN-LAST:event_TextFieldADMINIDKeyTyped

    private void TextFieldADMINIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldADMINIDKeyPressed
        // TODO add your handling code here:
        String accno=TextFieldADMINID.getText();
        int length=accno.length();
        if(length<5){
            TextFieldADMINID.setEditable(true);//If more than 10 ints, cant edit
        }
        else{
            TextFieldADMINID.setEditable(false);
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE |evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                TextFieldADMINID.setEditable(true);
            }
        }
    }//GEN-LAST:event_TextFieldADMINIDKeyPressed

    private void Textfield_PasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Textfield_PasswordKeyPressed
        // TODO add your handling code here:
        String accno=Textfield_Password.getText();
        int length=accno.length();
        if(length<6){
            Textfield_Password.setEditable(true);//If more than 10 ints, cant edit
        }
        else{
            Textfield_Password.setEditable(false);
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE |evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                Textfield_Password.setEditable(true);
            }
        }
    }//GEN-LAST:event_Textfield_PasswordKeyPressed

    private void Textfield_PasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Textfield_PasswordKeyTyped
        // TODO add your handling code here:
        char c= evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
    }    
    }//GEN-LAST:event_Textfield_PasswordKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADDADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADDADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADDADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADDADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADDADMIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonReset_Signuppanel;
    private javax.swing.JButton ButtonSignUp_Signuppanel;
    private javax.swing.JLabel LabelBACK_depositpanel;
    private javax.swing.JLabel LabelLogin;
    private javax.swing.JTextField TextFieldADMINID;
    private javax.swing.JTextField Textfield_ADMINNAME;
    private javax.swing.JTextField Textfield_Password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
