/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proj;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;


import java.sql.DriverManager;
import java.sql.ResultSet;

import java.sql.Statement;
import java.util.Locale;

/**
 *
 * @author irosh
 */
public class AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form AdminLogin
     */
    Connection conn;
    PreparedStatement pst;
    public AdminLogin() {
        initComponents();
    }
    Locale ll;
    public AdminLogin(Locale lcl) {
        Locale.setDefault(lcl);
        ll=lcl;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LabelLogin = new javax.swing.JLabel();
        LabelPIn = new javax.swing.JLabel();
        LabelAccNum1 = new javax.swing.JLabel();
        TextField_ID_adminpanel = new javax.swing.JTextField();
        ButtonLogin_loginpanel = new javax.swing.JButton();
        ButtonREset_loginpanel = new javax.swing.JButton();
        PasswordFieldPin_ADMINpanel = new javax.swing.JPasswordField();
        LabelLogout3 = new javax.swing.JLabel();
        LabelBACK_depositpanel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 153));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\irosh\\OneDrive\\Desktop\\JAVA\\Project\\Logo v3.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        LabelLogin.setFont(new java.awt.Font("Broadway", 0, 30)); // NOI18N
        LabelLogin.setForeground(new java.awt.Color(255, 255, 255));
        LabelLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle"); // NOI18N
        LabelLogin.setText(bundle.getString("AdminLogin.LabelLogin.text")); // NOI18N

        LabelPIn.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        LabelPIn.setForeground(new java.awt.Color(255, 255, 255));
        LabelPIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelPIn.setText(bundle.getString("AdminLogin.LabelPIn.text")); // NOI18N

        LabelAccNum1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        LabelAccNum1.setForeground(new java.awt.Color(255, 255, 255));
        LabelAccNum1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelAccNum1.setText(bundle.getString("AdminLogin.LabelAccNum1.text")); // NOI18N

        TextField_ID_adminpanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextField_ID_adminpanelKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_ID_adminpanelKeyTyped(evt);
            }
        });

        ButtonLogin_loginpanel.setForeground(new java.awt.Color(51, 0, 153));
        ButtonLogin_loginpanel.setText(bundle.getString("AdminLogin.ButtonLogin_loginpanel.text")); // NOI18N
        ButtonLogin_loginpanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogin_loginpanelActionPerformed(evt);
            }
        });

        ButtonREset_loginpanel.setForeground(new java.awt.Color(51, 0, 153));
        ButtonREset_loginpanel.setText(bundle.getString("AdminLogin.ButtonREset_loginpanel.text")); // NOI18N
        ButtonREset_loginpanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonREset_loginpanelActionPerformed(evt);
            }
        });

        PasswordFieldPin_ADMINpanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PasswordFieldPin_ADMINpanelKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PasswordFieldPin_ADMINpanelKeyTyped(evt);
            }
        });

        LabelLogout3.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        LabelLogout3.setForeground(new java.awt.Color(255, 255, 255));
        LabelLogout3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelLogout3.setText(bundle.getString("AdminLogin.LabelLogout3.text")); // NOI18N

        LabelBACK_depositpanel.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        LabelBACK_depositpanel.setForeground(new java.awt.Color(255, 0, 0));
        LabelBACK_depositpanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelBACK_depositpanel.setText(bundle.getString("AdminLogin.LabelBACK_depositpanel.text")); // NOI18N
        LabelBACK_depositpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelBACK_depositpanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(LabelBACK_depositpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(LabelAccNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TextField_ID_adminpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(LabelPIn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(53, 53, 53)
                                    .addComponent(PasswordFieldPin_ADMINpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(ButtonLogin_loginpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButtonREset_loginpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LabelLogout3, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ButtonLogin_loginpanel, ButtonREset_loginpanel});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_ID_adminpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelAccNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelPIn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PasswordFieldPin_ADMINpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonLogin_loginpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonREset_loginpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LabelBACK_depositpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(LabelLogout3))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_ID_adminpanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_ID_adminpanelKeyPressed
        // TODO add your handling code here:
        String accno=TextField_ID_adminpanel.getText();
        int length=accno.length();
        if(length<5){
            TextField_ID_adminpanel.setEditable(true);//If more than 10 ints, cant edit
        }
        else{
            TextField_ID_adminpanel.setEditable(false);
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE |evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                TextField_ID_adminpanel.setEditable(true);
            }
        }
    }//GEN-LAST:event_TextField_ID_adminpanelKeyPressed

    private void TextField_ID_adminpanelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_ID_adminpanelKeyTyped
        // TODO add your handling code here:
        char c= evt.getKeyChar();

        if(!Character.isDigit(c)){
            evt.consume();
        }

    }//GEN-LAST:event_TextField_ID_adminpanelKeyTyped

    private void ButtonLogin_loginpanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogin_loginpanelActionPerformed
        // TODO add your handling code here:
        if(TextField_ID_adminpanel.getText().isEmpty() || PasswordFieldPin_ADMINpanel.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Fields Can't be empty", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            int acid=Integer.parseInt(TextField_ID_adminpanel.getText());
            int pwfd=Integer.parseInt(PasswordFieldPin_ADMINpanel.getText());

            try{
                String url="jdbc:derby://localhost:1527/BankABC";
                Connection con=DriverManager.getConnection(url, "IROSH", "abc@123");
                Statement stmnt= con.createStatement();
                String qry="SELECT * FROM IROSH.ADMIN";
                ResultSet RS=stmnt.executeQuery(qry); //pointer start from -1.returns false when there are no more rows
                boolean ACwaradi=false,PWwaradi=false;
                while(RS.next()==true){
                    int oozanum=RS.getInt("ADMIN_ID");
                    int puz=RS.getInt("ADMIN_PW");
                    String nama=RS.getString("ADMIN_NAME");

                    if(acid==oozanum){
                        ACwaradi=false;

                        if(pwfd==puz){
                            JOptionPane.showMessageDialog(rootPane, "Welcome "+nama, "Success", JOptionPane.NO_OPTION);
                            new ADMIN(oozanum,ll).setVisible(true);
                            this.setVisible(false);
                            PWwaradi=false;
                            break;
                        }
                        else{
                            PWwaradi=true;
                            break;

                        }
                    }
                    else{
                        ACwaradi= true;

                    }
                }
                if(PWwaradi==true){
                    JOptionPane.showMessageDialog(rootPane, "Wrong Password.Try again", "Error", JOptionPane.ERROR_MESSAGE);
                    ButtonREset_loginpanelActionPerformed(evt);
                }
                if(ACwaradi==true){
                    JOptionPane.showMessageDialog(rootPane, "Wrong Account ID.Try again", "Error", JOptionPane.ERROR_MESSAGE);
                    ButtonREset_loginpanelActionPerformed(evt);
                }
            }
            catch(Exception e){
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_ButtonLogin_loginpanelActionPerformed

    private void ButtonREset_loginpanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonREset_loginpanelActionPerformed
        // TODO add your handling code here:
        TextField_ID_adminpanel.setText("");
        PasswordFieldPin_ADMINpanel.setText("");
    }//GEN-LAST:event_ButtonREset_loginpanelActionPerformed

    private void PasswordFieldPin_ADMINpanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordFieldPin_ADMINpanelKeyPressed
        // TODO add your handling code here:
        String accno=PasswordFieldPin_ADMINpanel.getText();
        int length=accno.length();
        if(length<6){
            PasswordFieldPin_ADMINpanel.setEditable(true);//If more than 10 ints, cant edit
        }
        else{
            PasswordFieldPin_ADMINpanel.setEditable(false);
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE |evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                PasswordFieldPin_ADMINpanel.setEditable(true);
            }
        }
    }//GEN-LAST:event_PasswordFieldPin_ADMINpanelKeyPressed

    private void PasswordFieldPin_ADMINpanelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PasswordFieldPin_ADMINpanelKeyTyped
        // TODO add your handling code here:
        char c= evt.getKeyChar();

        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_PasswordFieldPin_ADMINpanelKeyTyped

    private void LabelBACK_depositpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelBACK_depositpanelMouseClicked
        // TODO add your handling code here:
        new LOCALE().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabelBACK_depositpanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonLogin_loginpanel;
    private javax.swing.JButton ButtonREset_loginpanel;
    private javax.swing.JLabel LabelAccNum1;
    private javax.swing.JLabel LabelBACK_depositpanel;
    private javax.swing.JLabel LabelLogin;
    private javax.swing.JLabel LabelLogout3;
    private javax.swing.JLabel LabelPIn;
    private javax.swing.JPasswordField PasswordFieldPin_ADMINpanel;
    private javax.swing.JTextField TextField_ID_adminpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
