/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proj;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.sql.Statement;
import java.util.Locale;

/**
 *
 * @author irosh
 */
public class ADMIN extends javax.swing.JFrame {

    /**
     * Creates new form ADMIN
     */
    Connection conn;
    PreparedStatement pst;
    public ADMIN() {
        initComponents();
    }
    int adminid;
    Locale ll;
    public ADMIN(int adID,Locale lcl) {
        Locale.setDefault(lcl);
        ll=lcl;
        initComponents();
        adminid=adID;
        showDate();
        showTime();
        
        Label_accName_mainmenu.setText(""+adminid);
    }

    String DateRNN;
    public void showDate(){
        Date d=new Date();
        SimpleDateFormat SDF=new SimpleDateFormat("dd MMMM YYYY");
        String DateRN=SDF.format(d);
        String DateRNN=DateRN;
        TextFieldDate.setText(DateRN);
    }
    
    public void showTime(){
        new Timer(0,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                
        SimpleDateFormat sdft=new SimpleDateFormat("HH:mm:ss a");
        TextFieldTime.setText(sdft.format(d));
            }
                
            }).start();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LabelLogin = new javax.swing.JLabel();
        LabelLogin1 = new javax.swing.JLabel();
        Label_accName_mainmenu = new javax.swing.JLabel();
        BUTTON_viewattendancelog = new javax.swing.JButton();
        ButtonADDADMIN_Mainmenu = new javax.swing.JButton();
        ButtonViewTransaction_ADMINPANEL = new javax.swing.JButton();
        LabelLogout_mainmenu = new javax.swing.JLabel();
        LabelLogout1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextFieldDate = new javax.swing.JTextField();
        TextFieldTime = new javax.swing.JTextField();
        Button_EDITUSERaccs_adminpanel = new javax.swing.JButton();
        Button_ADDUSERaccs_adminpanel1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 153));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\irosh\\OneDrive\\Desktop\\JAVA\\Project\\Logo v3.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        LabelLogin.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        LabelLogin.setForeground(new java.awt.Color(255, 255, 255));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle"); // NOI18N
        LabelLogin.setText(bundle.getString("ADMIN.LabelLogin.text")); // NOI18N

        LabelLogin1.setFont(new java.awt.Font("Calibri", 0, 21)); // NOI18N
        LabelLogin1.setForeground(new java.awt.Color(255, 255, 255));
        LabelLogin1.setText(bundle.getString("ADMIN.LabelLogin1.text")); // NOI18N

        Label_accName_mainmenu.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Label_accName_mainmenu.setForeground(new java.awt.Color(255, 255, 255));

        BUTTON_viewattendancelog.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 11)); // NOI18N
        BUTTON_viewattendancelog.setForeground(new java.awt.Color(51, 0, 153));
        BUTTON_viewattendancelog.setText(bundle.getString("ADMIN.BUTTON_viewattendancelog.text")); // NOI18N
        BUTTON_viewattendancelog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_viewattendancelogActionPerformed(evt);
            }
        });

        ButtonADDADMIN_Mainmenu.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 11)); // NOI18N
        ButtonADDADMIN_Mainmenu.setForeground(new java.awt.Color(51, 0, 153));
        ButtonADDADMIN_Mainmenu.setText(bundle.getString("ADMIN.ButtonADDADMIN_Mainmenu.text")); // NOI18N
        ButtonADDADMIN_Mainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonADDADMIN_MainmenuActionPerformed(evt);
            }
        });

        ButtonViewTransaction_ADMINPANEL.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        ButtonViewTransaction_ADMINPANEL.setForeground(new java.awt.Color(51, 0, 153));
        ButtonViewTransaction_ADMINPANEL.setText(bundle.getString("ADMIN.ButtonViewTransaction_ADMINPANEL.text")); // NOI18N
        ButtonViewTransaction_ADMINPANEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonViewTransaction_ADMINPANELActionPerformed(evt);
            }
        });

        LabelLogout_mainmenu.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        LabelLogout_mainmenu.setForeground(new java.awt.Color(255, 0, 0));
        LabelLogout_mainmenu.setText(bundle.getString("ADMIN.LabelLogout_mainmenu.text")); // NOI18N
        LabelLogout_mainmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelLogout_mainmenuMouseClicked(evt);
            }
        });

        LabelLogout1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        LabelLogout1.setForeground(new java.awt.Color(255, 255, 255));
        LabelLogout1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelLogout1.setText(bundle.getString("ADMIN.LabelLogout1.text")); // NOI18N

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(bundle.getString("ADMIN.jLabel2.text")); // NOI18N

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(bundle.getString("ADMIN.jLabel3.text")); // NOI18N

        TextFieldTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldTimeActionPerformed(evt);
            }
        });

        Button_EDITUSERaccs_adminpanel.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        Button_EDITUSERaccs_adminpanel.setForeground(new java.awt.Color(51, 0, 153));
        Button_EDITUSERaccs_adminpanel.setText(bundle.getString("ADMIN.Button_EDITUSERaccs_adminpanel.text")); // NOI18N
        Button_EDITUSERaccs_adminpanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EDITUSERaccs_adminpanelActionPerformed(evt);
            }
        });

        Button_ADDUSERaccs_adminpanel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        Button_ADDUSERaccs_adminpanel1.setForeground(new java.awt.Color(51, 0, 153));
        Button_ADDUSERaccs_adminpanel1.setText(bundle.getString("ADMIN.Button_ADDUSERaccs_adminpanel1.text")); // NOI18N
        Button_ADDUSERaccs_adminpanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ADDUSERaccs_adminpanel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(TextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(LabelLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addComponent(Label_accName_mainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(TextFieldTime, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelLogin1)
                        .addGap(72, 72, 72)
                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(234, 234, 234))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BUTTON_viewattendancelog, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                            .addComponent(Button_EDITUSERaccs_adminpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonADDADMIN_Mainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonViewTransaction_ADMINPANEL))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LabelLogout_mainmenu)
                        .addGap(352, 352, 352))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Button_ADDUSERaccs_adminpanel1)
                                .addGap(223, 223, 223))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelLogout1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(282, 282, 282))))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BUTTON_viewattendancelog, ButtonADDADMIN_Mainmenu, ButtonViewTransaction_ADMINPANEL, Button_ADDUSERaccs_adminpanel1, Button_EDITUSERaccs_adminpanel});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_accName_mainmenu, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                                    .addComponent(LabelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TextFieldTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(LabelLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BUTTON_viewattendancelog, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Button_EDITUSERaccs_adminpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonViewTransaction_ADMINPANEL, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonADDADMIN_Mainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(Button_ADDUSERaccs_adminpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelLogout_mainmenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelLogout1)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Button_EDITUSERaccs_adminpanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EDITUSERaccs_adminpanelActionPerformed
        try {
            // TODO add your handling code here:
            int reply =Integer.parseInt(JOptionPane.showInputDialog("Please enter the current Account number : "));
            String url = "jdbc:derby://localhost:1527/BankABC";
            conn = DriverManager.getConnection(url, "IROSH", "abc@123");
            Statement stmnt= conn.createStatement();
            ResultSet RS=stmnt.executeQuery("Select * FROM ACCOUNT Where ACC_ID ="+reply);
            RS.next();
            int nikantemp=RS.getInt("ACC_ID");
            if (nikantemp==reply){
                new ADMIN_Useredit(nikantemp,adminid,ll).setVisible(true);
                this.dispose();
            }
            else{JOptionPane.showMessageDialog(rootPane, "Wrong Account number");}
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_Button_EDITUSERaccs_adminpanelActionPerformed

    private void TextFieldTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldTimeActionPerformed

    private void LabelLogout_mainmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelLogout_mainmenuMouseClicked
        // TODO add your handling code here:
        new LOCALE().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabelLogout_mainmenuMouseClicked

    private void ButtonViewTransaction_ADMINPANELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonViewTransaction_ADMINPANELActionPerformed
        // TODO add your handling code here:
//        try {
//            // TODO add your handling code here:
//            int reply =Integer.parseInt(JOptionPane.showInputDialog("Please enter the current Account number : "));
//            String url = "jdbc:derby://localhost:1527/BankABC";
//            conn = DriverManager.getConnection(url, "IROSH", "abc@123");
//            Statement stmnt= conn.createStatement();
//            ResultSet RS=stmnt.executeQuery("Select * FROM ACCOUNT Where ACC_ID ="+reply);
//            RS.next();
//            int nikantemp=RS.getInt("ACC_ID");
//            if (nikantemp==reply){
//                new ADMINVIEWTRANSACTIONS(reply).setVisible(true);
//                this.dispose();
//            }
//            else{JOptionPane.showMessageDialog(rootPane, "Wrong Account number");}
//        } catch (SQLException ex) {
//            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//        }

                new ADMINVIEWTRANSACTIONS(adminid,ll).setVisible(true);
                this.dispose();
    }//GEN-LAST:event_ButtonViewTransaction_ADMINPANELActionPerformed

    private void ButtonADDADMIN_MainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonADDADMIN_MainmenuActionPerformed
        // TODO add your handling code here:
        new ADDADMIN(adminid,ll).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonADDADMIN_MainmenuActionPerformed

    private void BUTTON_viewattendancelogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_viewattendancelogActionPerformed
        // TODO add your handling code here:
        new LoginLOG(adminid,ll).setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_BUTTON_viewattendancelogActionPerformed

    private void Button_ADDUSERaccs_adminpanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ADDUSERaccs_adminpanel1ActionPerformed
        // TODO add your handling code here:
        new ADMIN_ADDUSER(adminid,ll).setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_Button_ADDUSERaccs_adminpanel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADMIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUTTON_viewattendancelog;
    private javax.swing.JButton ButtonADDADMIN_Mainmenu;
    private javax.swing.JButton ButtonViewTransaction_ADMINPANEL;
    private javax.swing.JButton Button_ADDUSERaccs_adminpanel1;
    private javax.swing.JButton Button_EDITUSERaccs_adminpanel;
    private javax.swing.JLabel LabelLogin;
    private javax.swing.JLabel LabelLogin1;
    private javax.swing.JLabel LabelLogout1;
    private javax.swing.JLabel LabelLogout_mainmenu;
    private javax.swing.JLabel Label_accName_mainmenu;
    private javax.swing.JTextField TextFieldDate;
    private javax.swing.JTextField TextFieldTime;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
