/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proj;

import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Locale;

/**
 *
 * @author irosh
 */
public class DEPOSIT extends javax.swing.JFrame {

    /**
     * Creates new form DEPOSIT
     */
    
    Connection conn;
    PreparedStatement pst;
    public DEPOSIT() {
        initComponents();
    }
    int acccountnumber;
    Locale ll;
    public DEPOSIT(int acccno,Locale lcl) {
        Locale.setDefault(lcl);
        ll=lcl;
        initComponents();
        acccountnumber=acccno;
        TextField_accound_DepositPanel.setText(""+acccno);
        TextField_amount_DepositPanel.requestFocus();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LabelLogin = new javax.swing.JLabel();
        LabelAccNum1 = new javax.swing.JLabel();
        TextField_amount_DepositPanel = new javax.swing.JTextField();
        BUTTON_DEPOSIT_Depositpanel = new javax.swing.JButton();
        LabelLogout1 = new javax.swing.JLabel();
        LabelBACK_depositpanel1 = new javax.swing.JLabel();
        LabelAccNum2 = new javax.swing.JLabel();
        TextField_accound_DepositPanel = new javax.swing.JTextField();
        Button_Reset_Deposit_Panel = new javax.swing.JButton();
        LabelAccNum3 = new javax.swing.JLabel();
        Reference_DepositPanel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 153));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\irosh\\OneDrive\\Desktop\\JAVA\\Project\\Logo v3.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        LabelLogin.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        LabelLogin.setForeground(new java.awt.Color(255, 255, 255));
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle"); // NOI18N
        LabelLogin.setText(bundle.getString("DEPOSIT.LabelLogin.text")); // NOI18N

        LabelAccNum1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        LabelAccNum1.setForeground(new java.awt.Color(255, 255, 255));
        LabelAccNum1.setText(bundle.getString("DEPOSIT.LabelAccNum1.text")); // NOI18N

        TextField_amount_DepositPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextField_amount_DepositPanelKeyTyped(evt);
            }
        });

        BUTTON_DEPOSIT_Depositpanel.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        BUTTON_DEPOSIT_Depositpanel.setForeground(new java.awt.Color(51, 0, 153));
        BUTTON_DEPOSIT_Depositpanel.setText(bundle.getString("DEPOSIT.BUTTON_DEPOSIT_Depositpanel.text")); // NOI18N
        BUTTON_DEPOSIT_Depositpanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_DEPOSIT_DepositpanelActionPerformed(evt);
            }
        });

        LabelLogout1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        LabelLogout1.setForeground(new java.awt.Color(255, 255, 255));
        LabelLogout1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelLogout1.setText(bundle.getString("DEPOSIT.LabelLogout1.text")); // NOI18N

        LabelBACK_depositpanel1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        LabelBACK_depositpanel1.setForeground(new java.awt.Color(255, 0, 0));
        LabelBACK_depositpanel1.setText(bundle.getString("DEPOSIT.LabelBACK_depositpanel1.text")); // NOI18N
        LabelBACK_depositpanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelBACK_depositpanel1MouseClicked(evt);
            }
        });

        LabelAccNum2.setBackground(new java.awt.Color(255, 255, 255));
        LabelAccNum2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        LabelAccNum2.setForeground(new java.awt.Color(255, 255, 255));
        LabelAccNum2.setText(bundle.getString("DEPOSIT.LabelAccNum2.text")); // NOI18N

        TextField_accound_DepositPanel.setEditable(false);
        TextField_accound_DepositPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextField_accound_DepositPanelKeyPressed(evt);
            }
        });

        Button_Reset_Deposit_Panel.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        Button_Reset_Deposit_Panel.setForeground(new java.awt.Color(51, 0, 153));
        Button_Reset_Deposit_Panel.setText(bundle.getString("DEPOSIT.Button_Reset_Deposit_Panel.text")); // NOI18N
        Button_Reset_Deposit_Panel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_Reset_Deposit_PanelActionPerformed(evt);
            }
        });

        LabelAccNum3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        LabelAccNum3.setForeground(new java.awt.Color(255, 255, 255));
        LabelAccNum3.setText(bundle.getString("DEPOSIT.LabelAccNum3.text")); // NOI18N

        Reference_DepositPanel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Reference_DepositPanelKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelAccNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Reference_DepositPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BUTTON_DEPOSIT_Depositpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(Button_Reset_Deposit_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelBACK_depositpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelAccNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TextField_accound_DepositPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelAccNum1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextField_amount_DepositPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(173, 173, 173))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(LabelLogin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(LabelLogout1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAccNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_accound_DepositPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAccNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_amount_DepositPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAccNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reference_DepositPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BUTTON_DEPOSIT_Depositpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Reset_Deposit_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LabelBACK_depositpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelLogout1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public String setDate(){
        Date d=new Date();
        SimpleDateFormat SDF=new SimpleDateFormat("dd/MM/YYYY ");
        String DateRN=SDF.format(d);
        String DateRNN=DateRN;
        return DateRNN;
        
    }
    public String setTime(){
        
        Date d=new Date();
        SimpleDateFormat SDF=new SimpleDateFormat("hh:mm:ss a");
        String TimeRN=SDF.format(d);
        System.out.println(TimeRN);
        return TimeRN;
    }

    
    public int IDincrement() throws SQLException{
        
            String url = "jdbc:derby://localhost:1527/BankABC";
            conn = DriverManager.getConnection(url, "IROSH", "abc@123");
            Statement stmnt= conn.createStatement();
            ResultSet RS=stmnt.executeQuery("Select TID FROM TRANSACTIONS ORDER BY TID DESC ");
            if(RS.next()==true){
                int TIDtemp=RS.getInt(1); 
                
                return TIDtemp+1;
                
            }   
            else{
                return 1; 
            }
            
    }        
    
    private void DepositMoney(int amm){
        try {
            String url = "jdbc:derby://localhost:1527/BankABC";
            conn = DriverManager.getConnection(url, "IROSH", "abc@123");
//            Statement stmnt= conn.createStatement();
//            ResultSet RS=stmnt.executeQuery("Select * FROM ACCOUNT Where ACC_ID ="+temp_accno);
//            RS.next();
//            int nikantemp=RS.getInt("BALANCE"); //containts current balance
//            int totalBalance=nikantemp+ammnt;
            String Date=setDate();
            
            pst = conn.prepareStatement("INSERT INTO TRANSACTIONS VALUES (?,?,?,?,?,?,?)");
            
            pst.setInt(1,IDincrement());
            pst.setInt(2, acccountnumber);
            pst.setString(3, "Deposit");
            
            pst.setString(4, setDate());
            pst.setInt(5, amm);
            pst.setString(6, setTime());
            pst.setString(7, Reference_DepositPanel.getText());
            pst.executeUpdate();
            
//            JOptionPane.showMessageDialog(rootPane, "Record Updated ");
//            Button_Reset_Deposit_PanelActionPerformed(evt);
            
            
            
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    
    private void BUTTON_DEPOSIT_DepositpanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_DEPOSIT_DepositpanelActionPerformed
        // TODO add your handling code here:
        if(TextField_amount_DepositPanel.getText().isEmpty()|| TextField_amount_DepositPanel.getText().isEmpty() || Reference_DepositPanel.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Fields Cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            
        int ammnt=Integer.parseInt(TextField_amount_DepositPanel.getText());
        int temp_accno=Integer.parseInt(TextField_accound_DepositPanel.getText());
        
        try {
            String url = "jdbc:derby://localhost:1527/BankABC";
            conn = DriverManager.getConnection(url, "IROSH", "abc@123");
            Statement stmnt= conn.createStatement();
            ResultSet RS=stmnt.executeQuery("Select * FROM ACCOUNT Where ACC_ID ="+temp_accno);
            RS.next();
            int nikantemp=RS.getInt("BALANCE"); //containts current balance
            int totalBalance=nikantemp+ammnt;
            pst = conn.prepareStatement("UPDATE ACCOUNT SET BALANCE=? WHERE ACC_ID=?");
            pst.setInt(1, totalBalance);
            pst.setInt(2, temp_accno);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(rootPane, "Record Updated ");
            DepositMoney(ammnt);
            Button_Reset_Deposit_PanelActionPerformed(evt);
            
            
            
            
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
        
        }
    }//GEN-LAST:event_BUTTON_DEPOSIT_DepositpanelActionPerformed

    private void TextField_accound_DepositPanelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_accound_DepositPanelKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TextField_accound_DepositPanelKeyPressed

    private void TextField_amount_DepositPanelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextField_amount_DepositPanelKeyTyped
        // TODO add your handling code here:
        char c= evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_TextField_amount_DepositPanelKeyTyped

    private void Button_Reset_Deposit_PanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_Reset_Deposit_PanelActionPerformed
        // TODO add your handling code here:
        TextField_amount_DepositPanel.setText("");
        Reference_DepositPanel.setText("");
        
    }//GEN-LAST:event_Button_Reset_Deposit_PanelActionPerformed

    private void LabelBACK_depositpanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelBACK_depositpanel1MouseClicked
        // TODO add your handling code here:
        new MainMenu(Integer.parseInt(TextField_accound_DepositPanel.getText()),ll).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabelBACK_depositpanel1MouseClicked

    private void Reference_DepositPanelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Reference_DepositPanelKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Reference_DepositPanelKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DEPOSIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DEPOSIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DEPOSIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DEPOSIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DEPOSIT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUTTON_DEPOSIT_Depositpanel;
    private javax.swing.JButton Button_Reset_Deposit_Panel;
    private javax.swing.JLabel LabelAccNum1;
    private javax.swing.JLabel LabelAccNum2;
    private javax.swing.JLabel LabelAccNum3;
    private javax.swing.JLabel LabelBACK_depositpanel1;
    private javax.swing.JLabel LabelLogin;
    private javax.swing.JLabel LabelLogout1;
    private javax.swing.JTextField Reference_DepositPanel;
    private javax.swing.JTextField TextField_accound_DepositPanel;
    private javax.swing.JTextField TextField_amount_DepositPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
