/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proj;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.Timer;
import javax.swing.text.html.MinimalHTMLWriter;

/**
 *
 * @author irosh
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    Connection conn;
    PreparedStatement pst;

    public MainMenu() {
        initComponents();
        showDate();
        showTime();
    }
    int accountNO;
    Locale ll;
    public MainMenu(int acccno,Locale lcl) {
        Locale.setDefault(lcl);
        ll=lcl;
        initComponents();
        accountNO=acccno;
        showDate();
        showTime();
        

        Label_accName_mainmenu.setText("" + acccno);

    }
    
    String DateRNN;
    public void showDate(){
        Date d=new Date();
        SimpleDateFormat SDF=new SimpleDateFormat("dd MMMM YYYY");
        String DateRN=SDF.format(d);
        String DateRNN=DateRN;
        TextFieldDate.setText(DateRN);
    }
    
    public void showTime(){
        new Timer(0,new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date d = new Date();
                
        SimpleDateFormat sdft=new SimpleDateFormat("HH:mm:ss a");
        TextFieldTime.setText(sdft.format(d));
            }
                
            }).start();
        
    }

 
    
    public int getaccNum() {
        return Integer.parseInt(Label_accName_mainmenu.getText());
    }

//    public int getbalance(){
//        try {
//            String url = "jdbc:derby://localhost:1527/BankABC";
//            conn = DriverManager.getConnection(url, "IROSH", "abc@123");
//            Statement stmnt= conn.createStatement();
//            ResultSet RS=stmnt.executeQuery("Select * FROM ACCOUNT Where ACC_ID ="+getaccNum());
//            RS.next();
//            int nikantemp=RS.getInt("BALANCE"); //containts current balance
//            
//        }catch(Exception e){
//            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
//        }
//        
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LabelLogin = new javax.swing.JLabel();
        LabelLogin1 = new javax.swing.JLabel();
        Label_accName_mainmenu = new javax.swing.JLabel();
        ButtonDeposit_Mainmenu = new javax.swing.JButton();
        ButtonFastCash_Mainmenu = new javax.swing.JButton();
        ButtonWithdraw_Mainmenu = new javax.swing.JButton();
        ButtonPrintStatement_Mainmenu = new javax.swing.JButton();
        ButtonCheckBalance_Mainmenu = new javax.swing.JButton();
        LabelLogout_mainmenu = new javax.swing.JLabel();
        LabelLogout1 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextFieldDate = new javax.swing.JTextField();
        TextFieldTime = new javax.swing.JTextField();
        ButtonUpdatedelete_mainmenupanel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(806, 501));
        setPreferredSize(new java.awt.Dimension(713, 501));

        jPanel1.setBackground(new java.awt.Color(51, 0, 153));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\irosh\\OneDrive\\Desktop\\JAVA\\Project\\Logo v3.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        LabelLogin.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        LabelLogin.setForeground(new java.awt.Color(255, 255, 255));
        LabelLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle"); // NOI18N
        LabelLogin.setText(bundle.getString("MainMenu.LabelLogin.text")); // NOI18N

        LabelLogin1.setFont(new java.awt.Font("Calibri", 0, 21)); // NOI18N
        LabelLogin1.setForeground(new java.awt.Color(255, 255, 255));
        LabelLogin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelLogin1.setText(bundle.getString("MainMenu.LabelLogin1.text")); // NOI18N

        Label_accName_mainmenu.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Label_accName_mainmenu.setForeground(new java.awt.Color(255, 255, 255));

        ButtonDeposit_Mainmenu.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        ButtonDeposit_Mainmenu.setForeground(new java.awt.Color(51, 0, 153));
        ButtonDeposit_Mainmenu.setText(bundle.getString("MainMenu.ButtonDeposit_Mainmenu.text")); // NOI18N
        ButtonDeposit_Mainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeposit_MainmenuActionPerformed(evt);
            }
        });

        ButtonFastCash_Mainmenu.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        ButtonFastCash_Mainmenu.setForeground(new java.awt.Color(51, 0, 153));
        ButtonFastCash_Mainmenu.setText(bundle.getString("MainMenu.ButtonFastCash_Mainmenu.text")); // NOI18N
        ButtonFastCash_Mainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonFastCash_MainmenuActionPerformed(evt);
            }
        });

        ButtonWithdraw_Mainmenu.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        ButtonWithdraw_Mainmenu.setForeground(new java.awt.Color(51, 0, 153));
        ButtonWithdraw_Mainmenu.setText(bundle.getString("MainMenu.ButtonWithdraw_Mainmenu.text")); // NOI18N
        ButtonWithdraw_Mainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonWithdraw_MainmenuActionPerformed(evt);
            }
        });

        ButtonPrintStatement_Mainmenu.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 10)); // NOI18N
        ButtonPrintStatement_Mainmenu.setForeground(new java.awt.Color(51, 0, 153));
        ButtonPrintStatement_Mainmenu.setText(bundle.getString("MainMenu.ButtonPrintStatement_Mainmenu.text")); // NOI18N
        ButtonPrintStatement_Mainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPrintStatement_MainmenuActionPerformed(evt);
            }
        });

        ButtonCheckBalance_Mainmenu.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        ButtonCheckBalance_Mainmenu.setForeground(new java.awt.Color(51, 0, 153));
        ButtonCheckBalance_Mainmenu.setText(bundle.getString("MainMenu.ButtonCheckBalance_Mainmenu.text")); // NOI18N
        ButtonCheckBalance_Mainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCheckBalance_MainmenuActionPerformed(evt);
            }
        });

        LabelLogout_mainmenu.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        LabelLogout_mainmenu.setForeground(new java.awt.Color(255, 0, 0));
        LabelLogout_mainmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelLogout_mainmenu.setText(bundle.getString("MainMenu.LabelLogout_mainmenu.text")); // NOI18N
        LabelLogout_mainmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelLogout_mainmenuMouseClicked(evt);
            }
        });

        LabelLogout1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        LabelLogout1.setForeground(new java.awt.Color(255, 255, 255));
        LabelLogout1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelLogout1.setText(bundle.getString("MainMenu.LabelLogout1.text")); // NOI18N

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(bundle.getString("MainMenu.jLabel2.text")); // NOI18N

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(bundle.getString("MainMenu.jLabel3.text")); // NOI18N

        TextFieldTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldTimeActionPerformed(evt);
            }
        });

        ButtonUpdatedelete_mainmenupanel.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 10)); // NOI18N
        ButtonUpdatedelete_mainmenupanel.setForeground(new java.awt.Color(51, 0, 153));
        ButtonUpdatedelete_mainmenupanel.setText(bundle.getString("MainMenu.ButtonUpdatedelete_mainmenupanel.text")); // NOI18N
        ButtonUpdatedelete_mainmenupanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonUpdatedelete_mainmenupanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(234, 234, 234))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ButtonFastCash_Mainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ButtonDeposit_Mainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(ButtonCheckBalance_Mainmenu))
                                .addGap(135, 135, 135)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButtonWithdraw_Mainmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ButtonPrintStatement_Mainmenu, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(ButtonUpdatedelete_mainmenupanel, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(70, 70, 70))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextFieldTime, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(203, 203, 203)
                                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(LabelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Label_accName_mainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addComponent(LabelLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(254, 254, 254)
                                .addComponent(LabelLogout1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(106, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(LabelLogout_mainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ButtonCheckBalance_Mainmenu, ButtonDeposit_Mainmenu, ButtonFastCash_Mainmenu, ButtonPrintStatement_Mainmenu, ButtonUpdatedelete_mainmenupanel, ButtonWithdraw_Mainmenu});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Label_accName_mainmenu, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                                    .addComponent(LabelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TextFieldDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TextFieldTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonDeposit_Mainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonFastCash_Mainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonWithdraw_Mainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonPrintStatement_Mainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonCheckBalance_Mainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonUpdatedelete_mainmenupanel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(LabelLogout_mainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelLogout1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonDeposit_MainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeposit_MainmenuActionPerformed
        // TODO add your handling code here:
        new DEPOSIT(getaccNum(),ll).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonDeposit_MainmenuActionPerformed

    private void ButtonWithdraw_MainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonWithdraw_MainmenuActionPerformed
        // TODO add your handling code here:
        new WITHDRAW(getaccNum(),ll).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonWithdraw_MainmenuActionPerformed

    private void ButtonFastCash_MainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonFastCash_MainmenuActionPerformed
        // TODO add your handling code here:
        new FastCash(getaccNum(),ll).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonFastCash_MainmenuActionPerformed

    private void ButtonCheckBalance_MainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCheckBalance_MainmenuActionPerformed
        // TODO add your handling code here:
        new BALANCE(getaccNum(),ll).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ButtonCheckBalance_MainmenuActionPerformed

    private void TextFieldTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldTimeActionPerformed

    private void ButtonPrintStatement_MainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPrintStatement_MainmenuActionPerformed
        // TODO add your handling code here:
        new proj.Statement(getaccNum(),ll).setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_ButtonPrintStatement_MainmenuActionPerformed

    private void LabelLogout_mainmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelLogout_mainmenuMouseClicked
        // TODO add your handling code here:
        new LOCALE().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabelLogout_mainmenuMouseClicked

    private void ButtonUpdatedelete_mainmenupanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonUpdatedelete_mainmenupanelActionPerformed
        try {
            // TODO add your handling code here:
            int reply =Integer.parseInt(JOptionPane.showInputDialog("Please enter the current PIN number : "));
            String url = "jdbc:derby://localhost:1527/BankABC";
            conn = DriverManager.getConnection(url, "IROSH", "abc@123");
            Statement stmnt= conn.createStatement();
            ResultSet RS=stmnt.executeQuery("Select * FROM ACCOUNT Where ACC_ID ="+accountNO);
            RS.next();
            int nikantemp=RS.getInt("PIN"); 
            if (nikantemp==reply){
                new Update_delete(getaccNum(),ll).setVisible(true);
                this.dispose();
            }
            else{JOptionPane.showMessageDialog(rootPane, "Wrong pin number");}
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ButtonUpdatedelete_mainmenupanelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCheckBalance_Mainmenu;
    private javax.swing.JButton ButtonDeposit_Mainmenu;
    private javax.swing.JButton ButtonFastCash_Mainmenu;
    private javax.swing.JButton ButtonPrintStatement_Mainmenu;
    private javax.swing.JButton ButtonUpdatedelete_mainmenupanel;
    private javax.swing.JButton ButtonWithdraw_Mainmenu;
    private javax.swing.JLabel LabelLogin;
    private javax.swing.JLabel LabelLogin1;
    private javax.swing.JLabel LabelLogout1;
    private javax.swing.JLabel LabelLogout_mainmenu;
    private javax.swing.JLabel Label_accName_mainmenu;
    private javax.swing.JTextField TextFieldDate;
    private javax.swing.JTextField TextFieldTime;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
