/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proj;
import java.awt.event.*;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author irosh
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    Connection conn;
    PreparedStatement pst;
    public SignUp() {
        initComponents();
    }
    Locale ll;
    public SignUp(Locale lcl) {
        Locale.setDefault(lcl);
        ll=lcl;
        
        initComponents();
    }

    public void Clear(){
        TextFieldACCNUMBER.setText("");
        TextFieldName.setText("");
        TextFieldPhone.setText("");
        TextFieldAGe.setText("");
        TextFieldADDRESS.setText("");
        TextFieldEDUCATION.setText("");
        TextFieldOCCUPATION.setText("");
        TextFieldPIN.setText("");
        TextFieldACCNUMBER.setText("");
        jDateChooser1.setCalendar(null);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelLogout1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextFieldACCNUMBER = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextFieldName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextFieldAGe = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TextFieldADDRESS = new javax.swing.JTextField();
        TextFieldPIN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TextFieldEDUCATION = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TextFieldOCCUPATION = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TextFieldPhone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ButtonSignUp_Signuppanel = new javax.swing.JButton();
        ButtonReset_Signuppanel = new javax.swing.JButton();
        LabelLogin = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        LabelBACK_depositpanel = new javax.swing.JLabel();

        LabelLogout1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle"); // NOI18N
        LabelLogout1.setText(bundle.getString("SignUp.LabelLogout1.text")); // NOI18N

        jLabel11.setText(bundle.getString("SignUp.jLabel11.text")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 153));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\irosh\\OneDrive\\Desktop\\JAVA\\Project\\Logo v3.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(bundle.getString("SignUp.jLabel2.text")); // NOI18N

        TextFieldACCNUMBER.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextFieldACCNUMBERKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldACCNUMBERKeyTyped(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(bundle.getString("SignUp.jLabel3.text")); // NOI18N

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(bundle.getString("SignUp.jLabel4.text")); // NOI18N

        TextFieldAGe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldAGeKeyTyped(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(bundle.getString("SignUp.jLabel5.text")); // NOI18N

        TextFieldPIN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextFieldPINKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldPINKeyTyped(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText(bundle.getString("SignUp.jLabel6.text")); // NOI18N

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(bundle.getString("SignUp.jLabel7.text")); // NOI18N

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText(bundle.getString("SignUp.jLabel8.text")); // NOI18N

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText(bundle.getString("SignUp.jLabel9.text")); // NOI18N

        TextFieldPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TextFieldPhoneKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldPhoneKeyTyped(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText(bundle.getString("SignUp.jLabel10.text")); // NOI18N

        ButtonSignUp_Signuppanel.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 15)); // NOI18N
        ButtonSignUp_Signuppanel.setForeground(new java.awt.Color(51, 0, 153));
        ButtonSignUp_Signuppanel.setText(bundle.getString("SignUp.ButtonSignUp_Signuppanel.text")); // NOI18N
        ButtonSignUp_Signuppanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSignUp_SignuppanelActionPerformed(evt);
            }
        });

        ButtonReset_Signuppanel.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 15)); // NOI18N
        ButtonReset_Signuppanel.setForeground(new java.awt.Color(51, 0, 153));
        ButtonReset_Signuppanel.setText(bundle.getString("SignUp.ButtonReset_Signuppanel.text")); // NOI18N
        ButtonReset_Signuppanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonReset_SignuppanelActionPerformed(evt);
            }
        });

        LabelLogin.setFont(new java.awt.Font("Broadway", 0, 18)); // NOI18N
        LabelLogin.setForeground(new java.awt.Color(255, 255, 255));
        LabelLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelLogin.setText(bundle.getString("SignUp.LabelLogin.text")); // NOI18N

        jDateChooser1.setDateFormatString(bundle.getString("SignUp.jDateChooser1.dateFormatString")); // NOI18N

        LabelBACK_depositpanel.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        LabelBACK_depositpanel.setForeground(new java.awt.Color(255, 0, 0));
        LabelBACK_depositpanel.setText(bundle.getString("SignUp.LabelBACK_depositpanel.text")); // NOI18N
        LabelBACK_depositpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelBACK_depositpanelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldACCNUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextFieldADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextFieldAGe, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ButtonSignUp_Signuppanel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(ButtonReset_Signuppanel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextFieldPIN)
                            .addComponent(TextFieldEDUCATION)
                            .addComponent(TextFieldOCCUPATION)
                            .addComponent(TextFieldPhone)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(73, 73, 73))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelBACK_depositpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ButtonReset_Signuppanel, ButtonSignUp_Signuppanel});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldACCNUMBER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldAGe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldADDRESS, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldPIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldEDUCATION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldOCCUPATION, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSignUp_Signuppanel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonReset_Signuppanel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LabelBACK_depositpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldPhoneKeyPressed
        // TODO add your handling code here:
        String Phonenum=TextFieldPhone.getText();
        int length=Phonenum.length();
        if(length<9){
            TextFieldPhone.setEditable(true);//If more than 10 ints, cant edit
        }
        else{
            TextFieldPhone.setEditable(false);
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE |evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                TextFieldPhone.setEditable(true);
            }
        }
    }//GEN-LAST:event_TextFieldPhoneKeyPressed

    
    private void ButtonSignUp_SignuppanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSignUp_SignuppanelActionPerformed
        // TODO add your handling code here:
        String thisaccno=TextFieldACCNUMBER.getText();
        
        
        try{
            String url="jdbc:derby://localhost:1527/BankABC";
            Connection con=DriverManager.getConnection(url, "IROSH", "abc@123"); 
            java.sql.Statement stmnt= con.createStatement();
            String qry="SELECT * FROM IROSH.ACCOUNT";
            ResultSet RS=stmnt.executeQuery(qry); //pointer start from -1.returns false when there are no more rows
            boolean accnowaradi=true;
            while(RS.next()==true){
                String accnoo=RS.getString("ACC_ID");
                
                
                if(thisaccno.equalsIgnoreCase(accnoo)){
                    accnowaradi=false;
                    break;
                    
                }
                else{
                   accnowaradi= true;
                   
                }
            }
            
            if(accnowaradi==false){
                JOptionPane.showMessageDialog(rootPane, "Account ID is already in Use.Try again", "Error", JOptionPane.OK_OPTION);
                
            }
            if(accnowaradi==true){
                try {
                        
                        if(TextFieldACCNUMBER.getText().isEmpty() || TextFieldName.getText().isEmpty() || TextFieldAGe.getText().isEmpty() ||  TextFieldPhone.getText().isEmpty() || TextFieldADDRESS.getText().isEmpty() || TextFieldEDUCATION.getText().isEmpty() || TextFieldOCCUPATION.getText().isEmpty() || TextFieldPIN.getText().isEmpty()){
                             JOptionPane.showMessageDialog(rootPane, "Missing Information", "Error", JOptionPane.NO_OPTION);
                        }
                        else{  
                            url = "jdbc:derby://localhost:1527/BankABC";
                            conn = DriverManager.getConnection(url, "IROSH", "abc@123");
                            String date=((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
                            pst = conn.prepareStatement("INSERT INTO IROSH.ACCOUNT VALUES (?,?,?,?,?,?,?,?,?,?)");
                            pst.setInt(1, Integer.parseInt(TextFieldACCNUMBER.getText()));
                            pst.setString(2, TextFieldName.getText());
                            pst.setInt(3, Integer.parseInt(TextFieldPhone.getText()));
                            pst.setInt(4, Integer.parseInt(TextFieldAGe .getText()));
                            pst.setString(5, TextFieldADDRESS.getText());
                            pst.setString(6, date);
                            pst.setString(7, TextFieldEDUCATION.getText());
                            pst.setString(8, TextFieldOCCUPATION.getText());
                            pst.setInt(9, 0);  
                            pst.setInt(10, Integer.parseInt(TextFieldPIN.getText()));
                            

                            pst.executeUpdate();

                            JOptionPane.showMessageDialog(rootPane, "Accound added");
                            Clear();
                            

                //                Date d= new Date();
                //                DateFormat df= DateFormat.getDateTimeInstance(DateFormat.FULL, DateFormat.FULL);
                //                File f=new File("C:\\Users\\irosh\\OneDrive\\Desktop\\Log.txt");
                //                FileWriter fw=new FileWriter(f, true); //When 2nd parameter is true, files write from the end of the index and wont replace values
                //                fw.write("Record added "+TextFieldID.getText()+" "+df.format(d)+"\n" );
                //                fw.flush();
                //                fw.close();
                        }


                    }catch(Exception e){
                        JOptionPane.showMessageDialog(rootPane, e.getMessage(), "error", JOptionPane.ERROR_MESSAGE);
                    }
                
                
            }
            
        }
        catch(Exception e){
                    System.out.println(e.getMessage());
        }
        
        
        
        
        
        
    }//GEN-LAST:event_ButtonSignUp_SignuppanelActionPerformed

    private void ButtonReset_SignuppanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonReset_SignuppanelActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_ButtonReset_SignuppanelActionPerformed

    private void TextFieldACCNUMBERKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldACCNUMBERKeyPressed
        // TODO add your handling code here:
        String accno=TextFieldACCNUMBER.getText();
        int length=accno.length();
        if(length<6){
            TextFieldACCNUMBER.setEditable(true);//If more than 10 ints, cant edit
        }
        else{
            TextFieldACCNUMBER.setEditable(false);
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE |evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                TextFieldACCNUMBER.setEditable(true);
            }
        }
        
    }//GEN-LAST:event_TextFieldACCNUMBERKeyPressed

    private void TextFieldPINKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldPINKeyPressed
        // TODO add your handling code here:
        String accno=TextFieldPIN.getText();
        int length=accno.length();
        if(length<4){
            TextFieldPIN.setEditable(true);//If more than 10 ints, cant edit
        }
        else{
            TextFieldPIN.setEditable(false);
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE |evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                TextFieldPIN.setEditable(true);
            }
        }
        
    }//GEN-LAST:event_TextFieldPINKeyPressed

    private void TextFieldACCNUMBERKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldACCNUMBERKeyTyped
        // TODO add your handling code here:
        char c= evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();}
    }//GEN-LAST:event_TextFieldACCNUMBERKeyTyped

    private void TextFieldPINKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldPINKeyTyped
        // TODO add your handling code here:
        char c= evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();}
    }//GEN-LAST:event_TextFieldPINKeyTyped

    private void TextFieldPhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldPhoneKeyTyped
        // TODO add your handling code here:
        char c= evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_TextFieldPhoneKeyTyped

    private void LabelBACK_depositpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelBACK_depositpanelMouseClicked
        // TODO add your handling code here:
        new LOCALE().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabelBACK_depositpanelMouseClicked

    private void TextFieldAGeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldAGeKeyTyped
        // TODO add your handling code here:
        char c= evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();}
    
    }//GEN-LAST:event_TextFieldAGeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonReset_Signuppanel;
    private javax.swing.JButton ButtonSignUp_Signuppanel;
    private javax.swing.JLabel LabelBACK_depositpanel;
    private javax.swing.JLabel LabelLogin;
    private javax.swing.JLabel LabelLogout1;
    private javax.swing.JTextField TextFieldACCNUMBER;
    private javax.swing.JTextField TextFieldADDRESS;
    private javax.swing.JTextField TextFieldAGe;
    private javax.swing.JTextField TextFieldEDUCATION;
    private javax.swing.JTextField TextFieldName;
    private javax.swing.JTextField TextFieldOCCUPATION;
    private javax.swing.JTextField TextFieldPIN;
    private javax.swing.JTextField TextFieldPhone;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
