/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proj;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
/**
 *
 * @author irosh
 */


public class WITHDRAW extends javax.swing.JFrame {

    /**
     * Creates new form Withdraw
     */
    Connection conn;
    PreparedStatement pst;
    public WITHDRAW() {
        initComponents();
    }
    int accountnum;
    Locale ll;
    public WITHDRAW(int acc,Locale lcl) {
        Locale.setDefault(lcl);
        ll=lcl;
        initComponents();
        try {
            accountnum=acc;
            String url = "jdbc:derby://localhost:1527/BankABC";
            conn = DriverManager.getConnection(url, "IROSH", "abc@123");
            java.sql.Statement stmnt= conn.createStatement();
            ResultSet RS=stmnt.executeQuery("Select * FROM ACCOUNT Where ACC_ID ="+acc);
            RS.next();
            int nikantemp=RS.getInt("BALANCE"); //containts current balance
            LabelBALANCE_Withdrawpanel.setText(""+nikantemp);
            
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }
    
    public String setDate(){
        Date d=new Date();
        SimpleDateFormat SDF=new SimpleDateFormat("dd/MM/YYYY");
        String DateRN=SDF.format(d);
        String DateRNN=DateRN;
        return DateRNN;
    }
    
    public String setTime(){
        
        Date d=new Date();
        SimpleDateFormat SDF=new SimpleDateFormat("hh:mm:ss a");
        String TimeRN=SDF.format(d);
        System.out.println(TimeRN);
        return TimeRN;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LabelLogin = new javax.swing.JLabel();
        LabelBACK_Withdrawpanel = new javax.swing.JLabel();
        LabelAccNum2 = new javax.swing.JLabel();
        TextField_Amount_Withdrawpanel = new javax.swing.JTextField();
        BUTTON_Withdraw_Withdrawpanel = new javax.swing.JButton();
        LabelBALANCE_Withdrawpanel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LabelLogout1 = new javax.swing.JLabel();
        Button_reset_Withdrawpanel = new javax.swing.JButton();
        LabelAccNum3 = new javax.swing.JLabel();
        Reference_withdrawpanel = new javax.swing.JTextField();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle"); // NOI18N
        jButton1.setText(bundle.getString("WITHDRAW.jButton1.text")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 153));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\irosh\\OneDrive\\Desktop\\JAVA\\Project\\Logo v3.png")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        LabelLogin.setFont(new java.awt.Font("Broadway", 0, 36)); // NOI18N
        LabelLogin.setForeground(new java.awt.Color(255, 255, 255));
        LabelLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelLogin.setText(bundle.getString("WITHDRAW.LabelLogin.text")); // NOI18N

        LabelBACK_Withdrawpanel.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        LabelBACK_Withdrawpanel.setForeground(new java.awt.Color(255, 0, 0));
        LabelBACK_Withdrawpanel.setText(bundle.getString("WITHDRAW.LabelBACK_Withdrawpanel.text")); // NOI18N
        LabelBACK_Withdrawpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelBACK_WithdrawpanelMouseClicked(evt);
            }
        });

        LabelAccNum2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        LabelAccNum2.setForeground(new java.awt.Color(255, 255, 255));
        LabelAccNum2.setText(bundle.getString("WITHDRAW.LabelAccNum2.text")); // NOI18N

        BUTTON_Withdraw_Withdrawpanel.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        BUTTON_Withdraw_Withdrawpanel.setForeground(new java.awt.Color(51, 0, 153));
        BUTTON_Withdraw_Withdrawpanel.setText(bundle.getString("WITHDRAW.BUTTON_Withdraw_Withdrawpanel.text")); // NOI18N
        BUTTON_Withdraw_Withdrawpanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTTON_Withdraw_WithdrawpanelActionPerformed(evt);
            }
        });

        LabelBALANCE_Withdrawpanel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(bundle.getString("WITHDRAW.jLabel3.text")); // NOI18N

        LabelLogout1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        LabelLogout1.setForeground(new java.awt.Color(255, 255, 255));
        LabelLogout1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelLogout1.setText(bundle.getString("WITHDRAW.LabelLogout1.text")); // NOI18N

        Button_reset_Withdrawpanel.setFont(new java.awt.Font("sansserif", 0, 20)); // NOI18N
        Button_reset_Withdrawpanel.setForeground(new java.awt.Color(51, 0, 153));
        Button_reset_Withdrawpanel.setText(bundle.getString("WITHDRAW.Button_reset_Withdrawpanel.text")); // NOI18N
        Button_reset_Withdrawpanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_reset_WithdrawpanelActionPerformed(evt);
            }
        });

        LabelAccNum3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        LabelAccNum3.setForeground(new java.awt.Color(255, 255, 255));
        LabelAccNum3.setText(bundle.getString("WITHDRAW.LabelAccNum3.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BUTTON_Withdraw_Withdrawpanel)
                        .addGap(18, 18, 18)
                        .addComponent(Button_reset_Withdrawpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelAccNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Reference_withdrawpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LabelAccNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextField_Amount_Withdrawpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(80, 80, 80))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(LabelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabelBALANCE_Withdrawpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelBACK_Withdrawpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(205, 205, 205))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelLogout1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BUTTON_Withdraw_Withdrawpanel, Button_reset_Withdrawpanel});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelBALANCE_Withdrawpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAccNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_Amount_Withdrawpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelAccNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Reference_withdrawpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BUTTON_Withdraw_Withdrawpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_reset_Withdrawpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelBACK_Withdrawpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LabelLogout1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public int IDincrement() throws SQLException{
        
            String url = "jdbc:derby://localhost:1527/BankABC";
            conn = DriverManager.getConnection(url, "IROSH", "abc@123");
            Statement stmnt= conn.createStatement();
            ResultSet RS=stmnt.executeQuery("Select TID FROM TRANSACTIONS ORDER BY TID DESC ");
            if(RS.next()==true){
                int TIDtemp=RS.getInt(1); 
                return TIDtemp+1;
                
            }   
            else{
                return 1; 
            }
            
    }        
            
            
            
    
    private void WithdrawMOney(int amm){
        try {
            String url = "jdbc:derby://localhost:1527/BankABC";
            conn = DriverManager.getConnection(url, "IROSH", "abc@123");
//            Statement stmnt= conn.createStatement();
//            ResultSet RS=stmnt.executeQuery("Select * FROM ACCOUNT Where ACC_ID ="+temp_accno);
//            RS.next();
//            int nikantemp=RS.getInt("BALANCE"); //containts current balance
//            int totalBalance=nikantemp+ammnt;
            pst = conn.prepareStatement("INSERT INTO TRANSACTIONS VALUES (?,?,?,?,?,?,?)");
            
            pst.setInt(1,IDincrement());
            pst.setInt(2, accountnum);
            pst.setString(3, "Withdraw");
            
            pst.setString(4, setDate());
            pst.setString(6, setTime());
            pst.setString(7, Reference_withdrawpanel.getText());
            
            pst.setInt(5, amm);
            
            pst.executeUpdate();
            
//            JOptionPane.showMessageDialog(rootPane, "Record Updated ");
//            Button_Reset_Deposit_PanelActionPerformed(evt);
            
            
            
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    private void BUTTON_Withdraw_WithdrawpanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTTON_Withdraw_WithdrawpanelActionPerformed
        // TODO add your handling code here:
        if(TextField_Amount_Withdrawpanel.getText().isEmpty() || Reference_withdrawpanel.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Fields Cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            
        int ammnt=Integer.parseInt(TextField_Amount_Withdrawpanel.getText());
        int temp_accno=accountnum;
        
        try{
            String url = "jdbc:derby://localhost:1527/BankABC";
            conn = DriverManager.getConnection(url, "IROSH", "abc@123");
            Statement stmnt= conn.createStatement();
            ResultSet RS=stmnt.executeQuery("Select * FROM ACCOUNT Where ACC_ID ="+temp_accno);
            RS.next();
            int nikantemp=RS.getInt("BALANCE"); //containts current balance
            if(ammnt>nikantemp){
                JOptionPane.showMessageDialog(rootPane, "NOT ENOUGH MONEY!", "YOU ARE BROKE", JOptionPane.ERROR_MESSAGE);
                Button_reset_WithdrawpanelActionPerformed(evt);
            }
            if(ammnt<nikantemp){
                int totalBalance=nikantemp-ammnt;
                pst = conn.prepareStatement("UPDATE ACCOUNT SET BALANCE=? WHERE ACC_ID=?");
                pst.setInt(1, totalBalance);
                pst.setInt(2, temp_accno);
                pst.executeUpdate();
                WithdrawMOney(ammnt);

                JOptionPane.showMessageDialog(rootPane, "Money:  "+ammnt);
                Button_reset_WithdrawpanelActionPerformed(evt);
                LabelBALANCE_Withdrawpanel.setText(""+totalBalance);
            }
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "error", JOptionPane.ERROR_MESSAGE);
        }
        }
        
    }//GEN-LAST:event_BUTTON_Withdraw_WithdrawpanelActionPerformed

    private void Button_reset_WithdrawpanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_reset_WithdrawpanelActionPerformed
        // TODO add your handling code here:
        TextField_Amount_Withdrawpanel.setText("");
        Reference_withdrawpanel.setText("");
        
    }//GEN-LAST:event_Button_reset_WithdrawpanelActionPerformed

    private void LabelBACK_WithdrawpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelBACK_WithdrawpanelMouseClicked
        // TODO add your handling code here:
        new MainMenu(accountnum,ll).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabelBACK_WithdrawpanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WITHDRAW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WITHDRAW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WITHDRAW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WITHDRAW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WITHDRAW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUTTON_Withdraw_Withdrawpanel;
    private javax.swing.JButton Button_reset_Withdrawpanel;
    private javax.swing.JLabel LabelAccNum2;
    private javax.swing.JLabel LabelAccNum3;
    private javax.swing.JLabel LabelBACK_Withdrawpanel;
    private javax.swing.JLabel LabelBALANCE_Withdrawpanel;
    private javax.swing.JLabel LabelLogin;
    private javax.swing.JLabel LabelLogout1;
    private javax.swing.JTextField Reference_withdrawpanel;
    private javax.swing.JTextField TextField_Amount_Withdrawpanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
